// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDeploy() {
  return window['go']['app']['App']['CancelDeploy']();
}

export function CheckEnvironment(arg1) {
  return window['go']['app']['App']['CheckEnvironment'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['app']['App']['DeleteEnvironment'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['app']['App']['ExportConfig'](arg1);
}

export function GetAutoDetectJDK() {
  return window['go']['app']['App']['GetAutoDetectJDK']();
}

export function GetDeployHistory() {
  return window['go']['app']['App']['GetDeployHistory']();
}

export function GetDeployLogs(arg1) {
  return window['go']['app']['App']['GetDeployLogs'](arg1);
}

export function GetDeployProgress() {
  return window['go']['app']['App']['GetDeployProgress']();
}

export function GetEnvironment(arg1) {
  return window['go']['app']['App']['GetEnvironment'](arg1);
}

export function GetEnvironments() {
  return window['go']['app']['App']['GetEnvironments']();
}

export function GetGlobalSettings() {
  return window['go']['app']['App']['GetGlobalSettings']();
}

export function GetLastSelectedEnvID() {
  return window['go']['app']['App']['GetLastSelectedEnvID']();
}

export function GetSystemDefaults() {
  return window['go']['app']['App']['GetSystemDefaults']();
}

export function ImportConfig(arg1) {
  return window['go']['app']['App']['ImportConfig'](arg1);
}

export function ParseMavenCommand(arg1) {
  return window['go']['app']['App']['ParseMavenCommand'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['app']['App']['SaveEnvironment'](arg1);
}

export function SaveGlobalSettings(arg1) {
  return window['go']['app']['App']['SaveGlobalSettings'](arg1);
}

export function SaveSystemDefaults(arg1) {
  return window['go']['app']['App']['SaveSystemDefaults'](arg1);
}

export function SetDeployService(arg1) {
  return window['go']['app']['App']['SetDeployService'](arg1);
}

export function SetLastSelectedEnvID(arg1) {
  return window['go']['app']['App']['SetLastSelectedEnvID'](arg1);
}

export function StartDeploy(arg1) {
  return window['go']['app']['App']['StartDeploy'](arg1);
}

export function StartJDKDetection() {
  return window['go']['app']['App']['StartJDKDetection']();
}
