// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {response} from '../models';
import {request} from '../models';
import {service} from '../models';

export function CancelDeploy():Promise<response.Base>;

export function CheckEnvironment(arg1:request.CheckEnvironment):Promise<response.Data_deploy_tool_internal_model_entity_CheckResult_>;

export function DeleteEnvironment(arg1:request.DeleteEnvironment):Promise<response.Base>;

export function ExportConfig(arg1:request.ExportEnvironment):Promise<response.Data_string_>;

export function GetAutoDetectJDK():Promise<response.Data___map_string_string_>;

export function GetDeployHistory():Promise<response.Data___deploy_tool_internal_model_entity_DeployHistory_>;

export function GetDeployLogs(arg1:string):Promise<response.Data___deploy_tool_internal_model_entity_DeployLog_>;

export function GetDeployProgress():Promise<response.Data_deploy_tool_internal_model_entity_DeployProgress_>;

export function GetEnvironment(arg1:string):Promise<response.Data_deploy_tool_internal_model_entity_Environment_>;

export function GetEnvironments():Promise<response.Data___deploy_tool_internal_model_entity_Environment_>;

export function GetGlobalSettings():Promise<response.Data_deploy_tool_internal_model_entity_GlobalSettings_>;

export function GetSystemDefaults():Promise<response.Data_deploy_tool_internal_model_entity_SystemDefaultConfig_>;

export function ImportConfig(arg1:request.ImportEnvironment):Promise<response.Base>;

export function ParseMavenCommand(arg1:request.ParseMavenCommand):Promise<response.Data_deploy_tool_internal_service_MavenParseResult_>;

export function SaveEnvironment(arg1:request.SaveEnvironment):Promise<response.Base>;

export function SaveGlobalSettings(arg1:request.SaveGlobalSettings):Promise<response.Base>;

export function SaveSystemDefaults(arg1:request.SaveSystemDefaults):Promise<response.Base>;

export function SetDeployService(arg1:service.DeployService):Promise<void>;

export function StartDeploy(arg1:request.StartDeploy):Promise<response.Base>;

export function StartJDKDetection():Promise<response.Base>;
