// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelDeploy():Promise<void>;

export function CheckEnvironment(arg1:string):Promise<models.CheckResult>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function ExportConfig(arg1:string):Promise<string>;

export function GetDeployHistory():Promise<Array<models.DeployHistory>>;

export function GetDeployProgress():Promise<models.DeployProgress>;

export function GetEnvironment(arg1:string):Promise<models.Environment>;

export function GetEnvironments():Promise<Array<models.Environment>>;

export function GetGlobalSettings():Promise<models.GlobalSettings>;

export function GetSystemDefaults():Promise<models.SystemDefaultConfig>;

export function ImportConfig(arg1:string):Promise<void>;

export function SaveEnvironment(arg1:models.Environment):Promise<void>;

export function SaveGlobalSettings(arg1:models.GlobalSettings):Promise<void>;

export function SaveSystemDefaults(arg1:models.SystemDefaultConfig):Promise<void>;

export function StartDeploy(arg1:string,arg2:Array<string>):Promise<void>;
