// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDeploy() {
  return window['go']['main']['App']['CancelDeploy']();
}

export function CheckEnvironment(arg1) {
  return window['go']['main']['App']['CheckEnvironment'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GetDeployHistory() {
  return window['go']['main']['App']['GetDeployHistory']();
}

export function GetDeployProgress() {
  return window['go']['main']['App']['GetDeployProgress']();
}

export function GetEnvironment(arg1) {
  return window['go']['main']['App']['GetEnvironment'](arg1);
}

export function GetEnvironments() {
  return window['go']['main']['App']['GetEnvironments']();
}

export function GetGlobalSettings() {
  return window['go']['main']['App']['GetGlobalSettings']();
}

export function GetSystemDefaults() {
  return window['go']['main']['App']['GetSystemDefaults']();
}

export function ImportConfig(arg1) {
  return window['go']['main']['App']['ImportConfig'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveGlobalSettings(arg1) {
  return window['go']['main']['App']['SaveGlobalSettings'](arg1);
}

export function SaveSystemDefaults(arg1) {
  return window['go']['main']['App']['SaveSystemDefaults'](arg1);
}

export function StartDeploy(arg1, arg2) {
  return window['go']['main']['App']['StartDeploy'](arg1, arg2);
}
